### ISSUE TITLE
Gitter chat integration

### ISSUE THREAD

**Issue by franzliedke** [flarum/flarum.github.io#16]
The Gitter team just released [a new tool](https://sidecar.gitter.im/), which we could think about integrating on the website. :)

**Comment by franzliedke** [comment]
Or even on the forum, for that matter.

**Comment by rahulbohra** [comment]
Well, that's a good idea.
Admins can have there own chat room, as well as the other mods and members (public chat).

**Comment by tobyzerner** [comment]
Closing this as we no longer used Gitter 😈
