### ISSUE TITLE
nginx php matching is incorrect

### ISSUE THREAD

**Issue by luceos** [flarum/flarum.github.io#27]
```
location ~ .php$ {
```

The dot matches everything now because it's not escaped. It should be:

```
location ~ \.php$ {
```

**Comment by franzliedke** [comment]
Done. See https://github.com/flarum/flarum.github.io/commit/d224aca44d9196f8b0f8a8f03e1f617fea9dfe1e.

**Comment by luceos** [comment]
:+1:
