### ISSUE TITLE
Replace Source Sans Pro with Roboto

### ISSUE THREAD

**Issue by rodymolenaar** [flarum/flarum.github.io#42]
One thing that has always bothered me about flarum.org is how much of a pain it is to read the text (especially on windows). That's why I propose to use Roboto instead of Source Sans Pro. 
## Before

![Frontpage before](https://cloud.githubusercontent.com/assets/2954411/18817533/d71cfc46-8362-11e6-8fd5-8472b847c967.png)

![Docs before](http://i.imgur.com/JYIZK6r.png)
## After

![Frontpage after](http://i.imgur.com/kixpp5T.png)

![Docs after](http://i.imgur.com/71Lh7dQ.png)

**Comment by franzliedke** [comment]
Toby will have to decide this one. :)

**Comment by tobyzerner** [comment]
Good catch, thanks for reporting. Fixed. The issue was our use of the light variation of Source Sans Pro, not Source Sans Pro itself.

**Comment by franzliedke** [comment]
@tobscure That probably means we can get rid of the "300" in [this line](https://github.com/flarum/flarum.github.io/blob/da64ebcd8b66fd29f99adce11fae1c9bdc7b7248/_includes/head.html#L9) as well, right?

**Comment by tobyzerner** [comment]
@franzliedke Indeed!

**Comment by franzliedke** [comment]
Done in https://github.com/flarum/flarum.github.io/commit/c234070a04ab9618aeab489a620e568f7c28b0c6.

**Comment by tobyzerner** [comment]
Thanks!
