### ISSUE TITLE
Wrong GitHub repo link (?)

### ISSUE THREAD

**Issue by thomas-kuntz** [flarum/flarum.github.io#44]
Hi, I'm unsure wether the [link to the GitHub repo provided on the webiste](https://github.com/flarum/flarum) is correct. As far as I saw, the ['core' repo](https://github.com/flarum/core) looks like the main source code of the Flarum app, but the link points to this weird unactive repository...

So I was wondering if I just misunderstood something - in this case you'd better make all this more clear and obvious for the newcomer to the project like me 😉  - or if there really is an error on the website.

**Comment by franzliedke** [comment]
Closing this, as discussion can happen in the pull request.
