### ISSUE TITLE
Can't Receive discuss.flarum.org Verification Email

### ISSUE THREAD

**Issue by xmarco** [flarum/flarum.github.io#47]
Hi maintainers,

I can't receive verification email from https://discuss.flarum.org/ by Gmail (not in Spam neither). I need to have a full trial, but some features are restricted to unverified accounts.

Regards,
Marco

**Comment by xmarco** [comment]
It's working now.

**Comment by franzliedke** [comment]
Huh, weird. Glad you're on now, though.
