### ISSUE TITLE
Missing parameters for api

### ISSUE THREAD

**Issue by xiaohuilam** [flarum/flarum.github.io#68]
https://github.com/flarum/flarum.github.io/blob/master/_docs/api.md

**Comment by franzliedke** [comment]
Hello and thank you for your interest in Flarum.

Please provide detailed descriptions for any issues you create. This helps anybody involved in quickly understanding what this is about. If you expect these issues to be fixed, I would say it's only fair that we can expect as much input as possible. 

Closing until given further information. ;)
