### ISSUE TITLE
Add documentation for mail configuration

### ISSUE THREAD

**Issue by Southclaws** [flarum/flarum.github.io#76]
Loving Flarum, it's a nice lightweight alternative to Discourse!

However, I'm setting up the mail server configuration and noticed that there could be some documentation regarding the fields:

- Driver - what is this referring to? A PHP specific thing? The default value is simply `mail` so I left it at that, not sure what else could go here
- Host and Port - these are pretty self explanitory so probably nothing necessary here
- Encryption - it's a free text field, not really sure what to write here, `TLS`? `SSL/TLS`? `TLS/SSL`? `true`? `Yes please`?

(a "send test email" button would also be fantastic to ensure the settings are correct but that's more of a development thing than a docs thing so I'll head over the main repo for that one!)

**Comment by gwillem** [comment]
The mail config page could use some love indeed. Especially dropdowns for limited option sets, as a wrong input will brick your forum. See https://www.freeflarum.com/docs/howto/configure-mail/ for some examples

**Comment by franzliedke** [comment]
> (a "send test email" button would also be fantastic to ensure the settings are correct but that's more of a development thing than a docs thing so I'll head over the main repo for that one!)

Please do so, that's a great feature idea.

**Comment by franzliedke** [comment]
As for the documentation part, a PR would be awesome!
Right now, that should be sent to https://github.com/flarum/docs. We are in somewhat of a transition period here - the docs repo will serve the documentation on a new homepage. (Until that goes live, we will sync the contents to this repo from time to time.)

**Comment by gwillem** [comment]
FYI That request contradicts the readme of this repo, which was put there
because there was no eta on the doc migration and maintaining docs in two
places is not viable (they’ve diverged a lot already).

**Comment by franzliedke** [comment]
Hmm, okay, please follow the official document then. :speak_no_evil: 

I might have been mislead because the next version of the extension docs is currently being worked on in the other repository.

**Comment by franzliedke** [comment]
beta.9 significantly improved the editing experience of the mail driver settings. With flarum/core#1762 and flarum/core#1763 slated for the next beta, I am confident this will be self-documenting and intuitive enough that this is no longer needed... so I am closing this. :grinning:
