### ISSUE TITLE
Alignment of action list items

### ISSUE THREAD

**Issue by knrt10** [flarum/flarum.github.io#81]
![screen shot 2018-12-11 at 12 38 46 pm](https://user-images.githubusercontent.com/24803604/49783993-d00cc700-fd41-11e8-8929-f2f71f8e1127.png)

Action page items are not of the same height. I would like to fix this.

**Comment by luceos** [comment]
A new website is planned for and I certainly hope flexbox will be used ;)

**Comment by knrt10** [comment]
ok cool. then this issue is of no use. 😄
