### ISSUE TITLE
How do `/docs` can be accessed?

### ISSUE THREAD

**Issue by littlegolden** [flarum/flarum.github.io#85]
There is no `/docs` directory in `flarum.github.io` repository, what is the method that makes `https://flarum.org/docs/` exists? Don't `docs` repository need to be compiled?

**Comment by tankerkiller125** [comment]
We use nginx directory rules for the `/docs` directory I believe, all docs (and everything required to test them) can be found on the flarum/docs repo.

**Comment by littlegolden** [comment]
It looks like the flarum site is hosted on `github.io`, but I don't see the compiled `/docs` directory and any `html` files for the documents in the `flarum.github.io` repository, does it means that the website hosted on `github.io` can directly access the uncompiled vuepress document repository and then compile it online?

**Comment by dsevillamartin** [comment]
No. I don't know of this repository is used for anything anymore. We have another repo with the website that compiles the docs every time it's deployed - not through GitHub Pages.

**Comment by tankerkiller125** [comment]
@datitisev It appears that this repo is strictly here to redirect flarum.github.io to flarum.org at this point. We could probably empty all the actual contents and leave only the config and basic readme.

**Comment by askvortsov1** [comment]
If that's an option, we should do it. We should avoid confusing community members who want to contribute to the site. We should also probably disable the issue tracker for this repo.

**Comment by dsevillamartin** [comment]
We'll want to keep the issues because there's nowhere else for issue reporting.

**Comment by askvortsov1** [comment]
That would work too, but we should specify that in the Readme then.

**Comment by franzliedke** [comment]
Can this be closed then?

**Comment by askvortsov1** [comment]
Agreed, the purpose of this repo is now clear in the README.
