### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by dev-clavis** [flarum/flarum.github.io#88]
![image](https://user-images.githubusercontent.com/17059861/147051594-c46d4dd6-abad-4f9c-8284-66b5bc7d3d9f.png)

Just found this error, but I dont know if other also have this one.

PS: Merry Christmas

**Comment by askvortsov1** [comment]
Hey, thanks for the report! I'm unable to replicate this. What browser/OS are you using?

**Comment by dev-clavis** [comment]
# V
* OS: Win10
* Browser: Chrome
--
Edge wont work as well.

**Comment by davwheat** [comment]
I can't reproduce on any of my devices and browsers. This might be an issue with your internet connection or specific networking setup.

**Comment by dev-clavis** [comment]
Well I think so too, wasn't able to reproduce on other Network.
